import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/Video/PageTransition";
import HamburgerButton from "@/components/Menu/Mobile/HamburgerMenu";

// Configure the font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const jetBrains = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jet-brains",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetBrains.variable} antialiased text-custom-white-base text-xs font-inter`}
      >
        <PageTransition>
          {/* <HamburgerButton /> */}
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
