import { Inter, JetBrains_Mono, Nunito_Sans, Roboto } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/Video/PageTransition";
import HamburgerButton from "@/components/Menu/Mobile/HamburgerMenu";

// Configure the font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const jetBrains = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jet-brains",
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito-sans",
});

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetBrains.variable} ${nunitoSans.variable} ${roboto.variable} antialiased text-custom-white-base text-sm font-inter font-bold`}
      >
        <PageTransition>
          {/* <HamburgerButton /> */}
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
